# Jekyll configurations
markdown:     rdiscount
permalink:    /:categories/:title
exclude: compass, README.md, config.rb, .gitignore, Gemfile, Gemfile.lock, node_modules

# Jekyll server settings
auto:         true
server:       true
server_port:  4321

# Other custom settings
css:          /assets/css/
images:       /assets/images/
works_images: /assets/images/works/
name:         DesignThings
author:       Iryna Evseeva
email:        evseeva.iryna@gmail.com
slogan:       I live and eat design.
twitter:      irevseeva
availability: free
url:          http://designthings.github.com